import { registerSW } from 'virtual:pwa-register';

/**
 * Registers the service worker generated by vite-plugin-pwa and wires up
 * the update / offline-ready lifecycle callbacks.
 *
 * This module only handles registration and lifecycle plumbing — actual
 * caching strategy is defined in vite.config.ts (workbox config) and
 * request/response cache helpers live in src/offline/cacheStrategies.ts.
 *
 * TECH-004/DP-005 (SRS): built-in devotional content must keep working
 * offline, so failures here must never throw and block app startup.
 */

export type ServiceWorkerHooks = {
  /** Called when a new version is downloaded and ready to activate. */
  onNeedRefresh?: () => void;
  /** Called once the app has been fully cached for offline use. */
  onOfflineReady?: () => void;
  /** Called if registration itself fails (non-fatal). */
  onRegisterError?: (error: unknown) => void;
};

export function registerServiceWorker(hooks: ServiceWorkerHooks = {}): void {
  if (!('serviceWorker' in navigator)) {
    return;
  }

  try {
    const updateSW = registerSW({
      immediate: true,
      onNeedRefresh() {
        hooks.onNeedRefresh?.();
      },
      onOfflineReady() {
        hooks.onOfflineReady?.();
      },
      onRegisterError(error: unknown) {
        hooks.onRegisterError?.(error);
      },
    });

    // Exposed so a future "Update Available" UI action can trigger the
    // waiting worker to activate immediately (reloadPage = true).
    window.__swUpdate = () => updateSW(true);
  } catch (error) {
    hooks.onRegisterError?.(error);
  }
}

declare global {
  interface Window {
    __swUpdate?: () => Promise<void>;
  }
}
